// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShortenerEntities;

#nullable disable

namespace ShortenerEntities.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240821075951_UserNameIsUniqueConstraint")]
    partial class UserNameIsUniqueConstraint
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ShortenerEntities.ShortenedUrl", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LongUrl")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ShortUrl")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ShortenedUrls", (string)null);
                });

            modelBuilder.Entity("ShortenerEntities.User", b =>
                {
                    b.Property<Guid?>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("UserName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("14629847-905a-4a0e-9abe-80b61655c5cb"),
                            Password = "abcd1234",
                            UserName = "George"
                        },
                        new
                        {
                            UserId = new Guid("56bf46a4-02b8-4693-a0f5-0a95e2218bdc"),
                            Password = "abcd12345",
                            UserName = "Maksym"
                        },
                        new
                        {
                            UserId = new Guid("12e15727-d369-49a9-8b13-bc22e9362179"),
                            Password = "abcd123456",
                            UserName = "Marie"
                        },
                        new
                        {
                            UserId = new Guid("8f30bedc-47dd-4286-8950-73d8a68e5d41"),
                            Password = "abcd1234567",
                            UserName = "John"
                        },
                        new
                        {
                            UserId = new Guid("ea0075b4-e61d-48af-86d8-6c931aa493da"),
                            Password = "abcdef1234",
                            UserName = "Ivan"
                        });
                });

            modelBuilder.Entity("ShortenerEntities.ShortenedUrl", b =>
                {
                    b.HasOne("ShortenerEntities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
